

    export const Mock =   {
            "gid": "1259890070769369088;450000000000000;",
            "datatime": null,
            "datetype": null,
            "adcd": null,
            "adnm": null,
            "padcd": null,
            "level": null,
            "area": null,
            "channel": null,
            "wlevel": null,
            "warning": null,
            "details": [
                {
                    "id": 601,
                    "name": "行政区划与人口",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": null,
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 1,
                    "createtime": null,
                    "analyzed": 0,
                    "count": 4271886.6,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&601",
                    "children": [
                        {
                            "id": 401,
                            "name": "影响区县",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 1,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 1.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&401",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 402,
                            "name": "影响乡镇",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 2,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 9.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&402",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 50,
                            "name": "影响村庄",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": "VI_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 3,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 63.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&50",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 94,
                            "name": "人口",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": "POP_",
                            "unit": "人",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 4,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 1513901.0,
                            "details": null,
                            "mocds": [],
                            "uuid": null,
                            "children": null,
                            "mtype": null,
                            "loadMap": 0
                        },
                        {
                            "id": 95,
                            "name": "房屋数量",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": "HS_",
                            "unit": "栋",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 5,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 604421.0,
                            "details": null,
                            "mocds": [],
                            "uuid": null,
                            "children": null,
                            "mtype": null,
                            "loadMap": 0
                        },
                        {
                            "id": 96,
                            "name": "GDP",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": null,
                            "unit": "万元",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 6,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 2075318.0,
                            "details": null,
                            "mocds": [],
                            "uuid": null,
                            "children": null,
                            "mtype": null,
                            "loadMap": 0
                        },
                        {
                            "id": 400,
                            "name": "面积",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": null,
                            "unit": "km²",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 7,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 317.6,
                            "details": null,
                            "mocds": [],
                            "uuid": null,
                            "children": null,
                            "mtype": null,
                            "loadMap": 0
                        },
                        {
                            "id": 403,
                            "name": "农作物面积",
                            "parentid": 601,
                            "parentName": "行政区划与人口",
                            "level": null,
                            "remark": null,
                            "unit": "公顷",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 8,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 77856.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&403",
                            "children": null,
                            "mtype": null,
                            "loadMap": 0
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 632,
                    "name": "供水分析",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": null,
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 2,
                    "createtime": null,
                    "analyzed": 1,
                    "count": 0.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&632",
                    "children": [
                        {
                            "id": 633,
                            "name": "供水水源",
                            "parentid": 632,
                            "parentName": "供水分析",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 1,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&633",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 634,
                            "name": "农村供水工程",
                            "parentid": 632,
                            "parentName": "供水分析",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 2,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&634",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 635,
                            "name": "水柜工程",
                            "parentid": 632,
                            "parentName": "供水分析",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 3,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&635",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 603,
                    "name": "风险隐患点",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": "个",
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 2,
                    "createtime": null,
                    "analyzed": 0,
                    "count": 28.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&603",
                    "children": [
                        {
                            "id": 14,
                            "name": "山洪灾害危险区",
                            "parentid": 603,
                            "parentName": "风险隐患点",
                            "level": null,
                            "remark": "SH_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 4,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 28.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&14",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 609,
                    "name": "转移安置",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": "个",
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 3,
                    "createtime": null,
                    "analyzed": 0,
                    "count": 0.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&609",
                    "children": [
                        {
                            "id": 630,
                            "name": "安置点",
                            "parentid": 609,
                            "parentName": "转移安置",
                            "level": null,
                            "remark": "PL_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 8,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&630",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 631,
                            "name": "转移路线",
                            "parentid": 609,
                            "parentName": "转移安置",
                            "level": null,
                            "remark": "TR_",
                            "unit": "条",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 9,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&631",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 607,
                    "name": "监测站点",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": "个",
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 5,
                    "createtime": null,
                    "analyzed": 0,
                    "count": 29.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&607",
                    "children": [
                        {
                            "id": 4,
                            "name": "雨量站",
                            "parentid": 607,
                            "parentName": "监测站点",
                            "level": null,
                            "remark": "PP_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 1,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 28.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&4",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 15,
                            "name": "河道水文站",
                            "parentid": 607,
                            "parentName": "监测站点",
                            "level": null,
                            "remark": "ZQ_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 3,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 1.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&15",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 30,
                            "name": "墒情站",
                            "parentid": 607,
                            "parentName": "监测站点",
                            "level": null,
                            "remark": "SS_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 4,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&30",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 139,
                            "name": "监控视频",
                            "parentid": 607,
                            "parentName": "监测站点",
                            "level": null,
                            "remark": "VIDEO_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 5,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&139",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 605,
                    "name": "重点防护目标",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": "个",
                    "catagory": "关联信息",
                    "pinning": 0,
                    "ordernum": 7,
                    "createtime": null,
                    "analyzed": 0,
                    "count": 13.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&605",
                    "children": [
                        {
                            "id": 114,
                            "name": "病险水库",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "BX_",
                            "unit": "座",
                            "catagory": "风险影响",
                            "pinning": 1,
                            "ordernum": -6,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&114",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 1,
                            "name": "水库水电站",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "RR_",
                            "unit": "座",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": -1,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 13.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&1",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 52,
                            "name": "学校",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "SC_",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 1,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&52",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 54,
                            "name": "医院",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "HP_",
                            "unit": "个",
                            "catagory": "救援保障",
                            "pinning": 1,
                            "ordernum": 2,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&54",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 92,
                            "name": "车站",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 3,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&92",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 97,
                            "name": "机场",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": null,
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 4,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&97",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 93,
                            "name": "桥梁",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": null,
                            "unit": "座",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 5,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&93",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 420,
                            "name": "山塘",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "SHT_ 六枝特区山塘_资源数据",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 7,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&420",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 423,
                            "name": "自然保护区",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 8,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&423",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 425,
                            "name": "森林公园",
                            "parentid": 605,
                            "parentName": "重点防护目标",
                            "level": null,
                            "remark": "",
                            "unit": "个",
                            "catagory": "关联信息",
                            "pinning": 1,
                            "ordernum": 9,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&425",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 610,
                    "name": "救援力量",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": null,
                    "catagory": "救援力量",
                    "pinning": null,
                    "ordernum": 9,
                    "createtime": null,
                    "analyzed": null,
                    "count": 0.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&610",
                    "children": [
                        {
                            "id": 98,
                            "name": "地方防汛抗旱抢险队",
                            "parentid": 610,
                            "parentName": "救援力量",
                            "level": null,
                            "remark": null,
                            "unit": "支",
                            "catagory": "救援力量",
                            "pinning": 1,
                            "ordernum": 21,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&98",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 61,
                            "name": "消防救援队",
                            "parentid": 610,
                            "parentName": "救援力量",
                            "level": null,
                            "remark": "",
                            "unit": "支",
                            "catagory": "救援力量",
                            "pinning": 1,
                            "ordernum": 22,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&61",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        },
                        {
                            "id": 67,
                            "name": "社会救援队",
                            "parentid": 610,
                            "parentName": "救援力量",
                            "level": null,
                            "remark": null,
                            "unit": "支",
                            "catagory": "救援力量",
                            "pinning": 1,
                            "ordernum": 28,
                            "createtime": null,
                            "analyzed": 1,
                            "count": 0.0,
                            "details": null,
                            "mocds": [],
                            "uuid": "1259890070769369088;450000000000000;&67",
                            "children": null,
                            "mtype": null,
                            "loadMap": 1
                        }
                    ],
                    "mtype": null,
                    "loadMap": null
                },
                {
                    "id": 661,
                    "name": "无测站水库",
                    "parentid": null,
                    "parentName": null,
                    "level": null,
                    "remark": null,
                    "unit": "座",
                    "catagory": "关联信息",
                    "pinning": 1,
                    "ordernum": null,
                    "createtime": null,
                    "analyzed": 1,
                    "count": 0.0,
                    "details": null,
                    "mocds": [],
                    "uuid": "1259890070769369088;450000000000000;&661",
                    "children": null,
                    "mtype": null,
                    "loadMap": 1
                }
            ],
            "geoms": null,
            "wkt": null,
            "lowValue": null,
            "highValue": null,
            "adcdArea": null,
            "intersectArea": null,
            "percent": null,
            "source": null,
            "subCount": null,
            "count50": null,
            "count100": null,
            "count250": null,
            "avg": null,
            "briefIntroduction": "当前选定范围内，涉及区县1个、乡镇9个、人口1513901口、户数604421户。",
            "briefKeyObject": "范围内水库水电站13个，山洪危险区28个。",
            "createTime": null,
            "city": null,
            "county": null,
            "province": null,
            "adcdDetails": [],
            "createTimeFormat": null
        }
