/**
 * 专题图层信息
 */
const resource = [
  {
    id: 900,
    module: 2,
    datatype: null,
    name: null,
    icon: '/images/gis/jczy.png',
    checked: 0,
    level: 1,
    pid: 0,
    ordernum: 5,
    configure: null,
    sourcetype: 0,
    playable: 0,
    formable: 0,
    fileable: 0,
    legend: null,
    export: 0,
    motype: null,
    model: null,
    params: null,
    checkselect: '0',
    subs: [
      {
        id: 901,
        module: 2,
        datatype: 'layer_base_0',
        name: 'listen_id_371',
        icon: null,
        checked: 1,
        level: 2,
        pid: 900,
        ordernum: 1,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: null,
        export: 0,
        motype: 300,
        model: '1',
        params: null,
        checkselect: '1',
        subs: [],
        sttypes: null,
        rangeid: '0',
        label: '行政区划',
        anytimeable: '0',
        dailyable: 1,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 1,
        typename: null,
      },
      {
        id: 902,
        module: 2,
        datatype: 'layer_base_4',
        name: 'listen_id_372',
        icon: null,
        checked: 1,
        level: 2,
        pid: 900,
        ordernum: 2,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: null,
        export: 0,
        motype: 301,
        model: '1',
        params: null,
        checkselect: '1',
        subs: [],
        sttypes: null,
        rangeid: '0',
        label: '行政驻地',
        anytimeable: '0',
        dailyable: 1,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 2,
        typename: null,
      },
      {
        id: 910,
        module: 2,
        datatype: 'layer_base_910',
        name: 'listen_id_910',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 3,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 800,
        model: '2',
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '水系图层',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 9,
        typename: null,
      },
      // {
      //   id: 1103,
      //   module: 2,
      //   datatype: 'model',
      //   name: 'rsvr',
      //   icon: null,
      //   checked: 0,
      //   level: 2,
      //   pid: 900,
      //   ordernum: 4,
      //   configure: null,
      //   sourcetype: 2,
      //   playable: 0,
      //   formable: 1,
      //   fileable: 0,
      //   legend: null,
      //   export: 0,
      //   motype: 33,
      //   model: '4',
      //   params: null,
      //   checkselect: '1',
      //   subs: [],
      //   sttypes: null,
      //   rangeid: 'rsvr_interval',
      //   label: '三维模型',
      //   anytimeable: 'rsvr_anytime',
      //   dailyable: 1,
      //   hourable: null,
      //   lines: 0,
      //   typeid: null,
      //   typenum: 3,
      //   typename: null,
      // },
      {
        id: 903,
        module: 2,
        datatype: 'layer_base_9',
        name: 'listen_id_79',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 5,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 302,
        model: '2',
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '高程图',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 3,
        typename: null,
      },
      // {
      //   id: 904,
      //   module: 2,
      //   datatype: 'layer_base_1',
      //   name: 'listen_id_60',
      //   icon: null,
      //   checked: 0,
      //   level: 2,
      //   pid: 900,
      //   ordernum: 6,
      //   configure: null,
      //   sourcetype: 2,
      //   playable: 0,
      //   formable: 1,
      //   fileable: 0,
      //   legend: null,
      //   export: 0,
      //   motype: 642,
      //   model: '2',
      //   params: null,
      //   checkselect: '0',
      //   subs: [],
      //   sttypes: null,
      //   rangeid: null,
      //   label: '河流水系',
      //   anytimeable: null,
      //   dailyable: 0,
      //   hourable: null,
      //   lines: 0,
      //   typeid: null,
      //   typenum: 4,
      //   typename: null,
      // },
      {
        id: 905,
        module: 2,
        datatype: 'layer_base_3',
        name: 'listen_id_80',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 7,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: null,
        export: 0,
        motype: 303,
        model: '2',
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '交通路网',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 5,
        typename: null,
      },
      {
        id: 906,
        module: 2,
        datatype: 'layer_base_12',
        name: 'listen_id_81',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 8,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 304,
        model: null,
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '土地利用',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 6,
        typename: null,
      },
      {
        id: 907,
        module: 2,
        datatype: 'layer_base_10',
        name: 'listen_id_82',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 9,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 94,
        model: null,
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '人口分布',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 7,
        typename: null,
      },
      {
        id: 908,
        module: 2,
        datatype: 'layer_base_11',
        name: 'listen_id_83',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 10,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 96,
        model: null,
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: 'GDP分布',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 8,
        typename: null,
      },
      {
        id: 909,
        module: 2,
        datatype: 'layer_base_13',
        name: 'listen_id_84',
        icon: null,
        checked: 0,
        level: 2,
        pid: 900,
        ordernum: 11,
        configure: null,
        sourcetype: 5,
        playable: 0,
        formable: 0,
        fileable: 0,
        legend: {
          name: null,
          items: null,
          index: null,
          styletype: null,
          legendtype: 'img',
          img: null,
        },
        export: 0,
        motype: 95,
        model: null,
        params: null,
        checkselect: '0',
        subs: [],
        sttypes: null,
        rangeid: null,
        label: '房屋分布',
        anytimeable: null,
        dailyable: 0,
        hourable: null,
        lines: 0,
        typeid: null,
        typenum: 9,
        typename: null,
      },
      // 流向
      {
        id: 999,
        datatype: 'layer_base_911',
        sourcetype: 5,
        motype: 642,
        legend: null,
        label: '流向',
      },
    ],
    sttypes: null,
    rangeid: '0',
    label: '基础图层',
    anytimeable: '0',
    dailyable: 0,
    hourable: null,
    lines: 0,
    typeid: null,
    typenum: 5,
    typename: null,
  },
];

export { resource };
